name: incad
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - black
  - bottleneck
  - conda
  - conda-merge
  - conda-pack
  - h5py
  - imbalanced-learn
  - ipykernel
  - mamba
  - matplotlib
  - matplotlib-inline
  - numba
  - numpy
  - pandas
  - plotly
  - pip=22.2.2
  - polars
  - pyarrow
  - pylint
  - pytest
  - pytest-cov
  - python<3.11
  - pyyaml
  - ruff
  - scikit-learn
  - scipy
  - seaborn
  - six
  - spot
  - statsmodels
  - tqdm
  - xarray
  - zarr
  - pip:
    - apprise
    - boltons
    - drawdata
    - fugue[dask,duckdb,ibis,polars]
    - gdown
    - hypothesis
    - ptpython
    - weave